import customtkinter as ctk 
from perfil_usuario import *

class BotoesCategoria(JanelaUsuario):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        
    def verificar_botao_acao(self):
        if self.botao_acao._check_state == True:
            self.id_genero = 28
            self.botao_animacao.configure(state=DISABLED)
            self.botao_aventura.configure(state=DISABLED)
            self.botao_cinemaTV.configure(state=DISABLED)
            self.botao_comedia.configure(state=DISABLED)
            self.botao_crime.configure(state=DISABLED)
            self.botao_documentario.configure(state=DISABLED)
            self.botao_drama.configure(state=DISABLED)
            self.botao_familia.configure(state=DISABLED)
            self.botao_fantasia.configure(state=DISABLED)
            self.botao_faroeste.configure(state=DISABLED)
            self.botao_guerra.configure(state=DISABLED)
            self.botao_historia.configure(state=DISABLED)
            self.botao_misterio.configure(state=DISABLED)
            self.botao_musica.configure(state=DISABLED)
            self.botao_romance.configure(state=DISABLED)
            self.botao_scifi.configure(state=DISABLED)
            self.botao_terror.configure(state=DISABLED)
            self.botao_thriller.configure(state=DISABLED)       
        else:
            self.id_genero = None
            self.botao_animacao.configure(state=NORMAL)
            self.botao_aventura.configure(state=NORMAL)
            self.botao_cinemaTV.configure(state=NORMAL)
            self.botao_comedia.configure(state=NORMAL)
            self.botao_crime.configure(state=NORMAL)
            self.botao_documentario.configure(state=NORMAL)
            self.botao_drama.configure(state=NORMAL)
            self.botao_familia.configure(state=NORMAL)
            self.botao_fantasia.configure(state=NORMAL)
            self.botao_faroeste.configure(state=NORMAL)
            self.botao_guerra.configure(state=NORMAL)
            self.botao_historia.configure(state=NORMAL)
            self.botao_misterio.configure(state=NORMAL)
            self.botao_musica.configure(state=NORMAL)
            self.botao_romance.configure(state=NORMAL)
            self.botao_scifi.configure(state=NORMAL)
            self.botao_terror.configure(state=NORMAL)
            self.botao_thriller.configure(state=NORMAL)
    
    def verificar_botao_animacao(self):    
        if self.botao_animacao._check_state == True:
            self.id_genero = 16
            self.botao_acao.configure(state=DISABLED)
            self.botao_aventura.configure(state=DISABLED)
            self.botao_cinemaTV.configure(state=DISABLED)
            self.botao_comedia.configure(state=DISABLED)
            self.botao_crime.configure(state=DISABLED)
            self.botao_documentario.configure(state=DISABLED)
            self.botao_drama.configure(state=DISABLED)
            self.botao_familia.configure(state=DISABLED)
            self.botao_fantasia.configure(state=DISABLED)
            self.botao_faroeste.configure(state=DISABLED)
            self.botao_guerra.configure(state=DISABLED)
            self.botao_historia.configure(state=DISABLED)
            self.botao_misterio.configure(state=DISABLED)
            self.botao_musica.configure(state=DISABLED)
            self.botao_romance.configure(state=DISABLED)
            self.botao_scifi.configure(state=DISABLED)
            self.botao_terror.configure(state=DISABLED)
            self.botao_thriller.configure(state=DISABLED)
        else:
            self.id_genero = None
            self.botao_acao.configure(state=NORMAL)
            self.botao_aventura.configure(state=NORMAL)
            self.botao_cinemaTV.configure(state=NORMAL)
            self.botao_comedia.configure(state=NORMAL)
            self.botao_crime.configure(state=NORMAL)
            self.botao_documentario.configure(state=NORMAL)
            self.botao_drama.configure(state=NORMAL)
            self.botao_familia.configure(state=NORMAL)
            self.botao_fantasia.configure(state=NORMAL)
            self.botao_faroeste.configure(state=NORMAL)
            self.botao_guerra.configure(state=NORMAL)
            self.botao_historia.configure(state=NORMAL)
            self.botao_misterio.configure(state=NORMAL)
            self.botao_musica.configure(state=NORMAL)
            self.botao_romance.configure(state=NORMAL)
            self.botao_scifi.configure(state=NORMAL)
            self.botao_terror.configure(state=NORMAL)
            self.botao_thriller.configure(state=NORMAL)
    
    def verificar_botao_aventura(self):
        if self.botao_aventura._check_state == True:
            self.id_genero = 12
            self.botao_acao.configure(state=DISABLED)
            self.botao_animacao.configure(state=DISABLED)
            self.botao_cinemaTV.configure(state=DISABLED)
            self.botao_comedia.configure(state=DISABLED)
            self.botao_crime.configure(state=DISABLED)
            self.botao_documentario.configure(state=DISABLED)
            self.botao_drama.configure(state=DISABLED)
            self.botao_familia.configure(state=DISABLED)
            self.botao_fantasia.configure(state=DISABLED)
            self.botao_faroeste.configure(state=DISABLED)
            self.botao_guerra.configure(state=DISABLED)
            self.botao_historia.configure(state=DISABLED)
            self.botao_misterio.configure(state=DISABLED)
            self.botao_musica.configure(state=DISABLED)
            self.botao_romance.configure(state=DISABLED)
            self.botao_scifi.configure(state=DISABLED)
            self.botao_terror.configure(state=DISABLED)
            self.botao_thriller.configure(state=DISABLED)
        else:
            self.id_genero = None
            self.botao_acao.configure(state=NORMAL)
            self.botao_animacao.configure(state=NORMAL)
            self.botao_cinemaTV.configure(state=NORMAL)
            self.botao_comedia.configure(state=NORMAL)
            self.botao_crime.configure(state=NORMAL)
            self.botao_documentario.configure(state=NORMAL)
            self.botao_drama.configure(state=NORMAL)
            self.botao_familia.configure(state=NORMAL)
            self.botao_fantasia.configure(state=NORMAL)
            self.botao_faroeste.configure(state=NORMAL)
            self.botao_guerra.configure(state=NORMAL)
            self.botao_historia.configure(state=NORMAL)
            self.botao_misterio.configure(state=NORMAL)
            self.botao_musica.configure(state=NORMAL)
            self.botao_romance.configure(state=NORMAL)
            self.botao_scifi.configure(state=NORMAL)
            self.botao_terror.configure(state=NORMAL)
            self.botao_thriller.configure(state=NORMAL)    

    def verificar_botao_cinemaTV(self):
        if self.botao_cinemaTV._check_state == True:
            self.id_genero = 10770
            self.botao_acao.configure(state=DISABLED)
            self.botao_animacao.configure(state=DISABLED)
            self.botao_aventura.configure(state=DISABLED)
            self.botao_comedia.configure(state=DISABLED)
            self.botao_crime.configure(state=DISABLED)
            self.botao_documentario.configure(state=DISABLED)
            self.botao_drama.configure(state=DISABLED)
            self.botao_familia.configure(state=DISABLED)
            self.botao_fantasia.configure(state=DISABLED)
            self.botao_faroeste.configure(state=DISABLED)
            self.botao_guerra.configure(state=DISABLED)
            self.botao_historia.configure(state=DISABLED)
            self.botao_misterio.configure(state=DISABLED)
            self.botao_musica.configure(state=DISABLED)
            self.botao_romance.configure(state=DISABLED)
            self.botao_scifi.configure(state=DISABLED)
            self.botao_terror.configure(state=DISABLED)
            self.botao_thriller.configure(state=DISABLED)
        else:
            self.id_genero = None
            self.botao_acao.configure(state=NORMAL)
            self.botao_animacao.configure(state=NORMAL)
            self.botao_aventura.configure(state=NORMAL)
            self.botao_comedia.configure(state=NORMAL)
            self.botao_crime.configure(state=NORMAL)
            self.botao_documentario.configure(state=NORMAL)
            self.botao_drama.configure(state=NORMAL)
            self.botao_familia.configure(state=NORMAL)
            self.botao_fantasia.configure(state=NORMAL)
            self.botao_faroeste.configure(state=NORMAL)
            self.botao_guerra.configure(state=NORMAL)
            self.botao_historia.configure(state=NORMAL)
            self.botao_misterio.configure(state=NORMAL)
            self.botao_musica.configure(state=NORMAL)
            self.botao_romance.configure(state=NORMAL)
            self.botao_scifi.configure(state=NORMAL)
            self.botao_terror.configure(state=NORMAL)
            self.botao_thriller.configure(state=NORMAL) 
    
    def verificar_botao_comedia(self):
        if self.botao_comedia._check_state == True:
            self.id_genero = 35
            self.botao_acao.configure(state=DISABLED)
            self.botao_animacao.configure(state=DISABLED)
            self.botao_aventura.configure(state=DISABLED)
            self.botao_cinemaTV.configure(state=DISABLED)
            self.botao_crime.configure(state=DISABLED)
            self.botao_documentario.configure(state=DISABLED)
            self.botao_drama.configure(state=DISABLED)
            self.botao_familia.configure(state=DISABLED)
            self.botao_fantasia.configure(state=DISABLED)
            self.botao_faroeste.configure(state=DISABLED)
            self.botao_guerra.configure(state=DISABLED)
            self.botao_historia.configure(state=DISABLED)
            self.botao_misterio.configure(state=DISABLED)
            self.botao_musica.configure(state=DISABLED)
            self.botao_romance.configure(state=DISABLED)
            self.botao_scifi.configure(state=DISABLED)
            self.botao_terror.configure(state=DISABLED)
            self.botao_thriller.configure(state=DISABLED)
        else:
            self.id_genero = None
            self.botao_acao.configure(state=NORMAL)
            self.botao_animacao.configure(state=NORMAL)
            self.botao_aventura.configure(state=NORMAL)
            self.botao_cinemaTV.configure(state=NORMAL)
            self.botao_crime.configure(state=NORMAL)
            self.botao_documentario.configure(state=NORMAL)
            self.botao_drama.configure(state=NORMAL)
            self.botao_familia.configure(state=NORMAL)
            self.botao_fantasia.configure(state=NORMAL)
            self.botao_faroeste.configure(state=NORMAL)
            self.botao_guerra.configure(state=NORMAL)
            self.botao_historia.configure(state=NORMAL)
            self.botao_misterio.configure(state=NORMAL)
            self.botao_musica.configure(state=NORMAL)
            self.botao_romance.configure(state=NORMAL)
            self.botao_scifi.configure(state=NORMAL)
            self.botao_terror.configure(state=NORMAL)
            self.botao_thriller.configure(state=NORMAL)
            
    def verificar_botao_crime(self):
        if self.botao_crime._check_state == True:
            self.id_genero = 80
            self.botao_acao.configure(state=DISABLED)
            self.botao_animacao.configure(state=DISABLED)
            self.botao_aventura.configure(state=DISABLED)
            self.botao_cinemaTV.configure(state=DISABLED)
            self.botao_comedia.configure(state=DISABLED)
            self.botao_documentario.configure(state=DISABLED)
            self.botao_drama.configure(state=DISABLED)
            self.botao_familia.configure(state=DISABLED)
            self.botao_fantasia.configure(state=DISABLED)
            self.botao_faroeste.configure(state=DISABLED)
            self.botao_guerra.configure(state=DISABLED)
            self.botao_historia.configure(state=DISABLED)
            self.botao_misterio.configure(state=DISABLED)
            self.botao_musica.configure(state=DISABLED)
            self.botao_romance.configure(state=DISABLED)
            self.botao_scifi.configure(state=DISABLED)
            self.botao_terror.configure(state=DISABLED)
            self.botao_thriller.configure(state=DISABLED)
        else:
            self.id_genero = None
            self.botao_acao.configure(state=NORMAL)
            self.botao_animacao.configure(state=NORMAL)
            self.botao_aventura.configure(state=NORMAL)
            self.botao_cinemaTV.configure(state=NORMAL)
            self.botao_comedia.configure(state=NORMAL)
            self.botao_documentario.configure(state=NORMAL)
            self.botao_drama.configure(state=NORMAL)
            self.botao_familia.configure(state=NORMAL)
            self.botao_fantasia.configure(state=NORMAL)
            self.botao_faroeste.configure(state=NORMAL)
            self.botao_guerra.configure(state=NORMAL)
            self.botao_historia.configure(state=NORMAL)
            self.botao_misterio.configure(state=NORMAL)
            self.botao_musica.configure(state=NORMAL)
            self.botao_romance.configure(state=NORMAL)
            self.botao_scifi.configure(state=NORMAL)
            self.botao_terror.configure(state=NORMAL)
            self.botao_thriller.configure(state=NORMAL)
    
    def verificar_botao_documentario(self):
        if self.botao_documentario._check_state == True:
            self.id_genero = 99
            self.botao_acao.configure(state=DISABLED)
            self.botao_animacao.configure(state=DISABLED)
            self.botao_aventura.configure(state=DISABLED)
            self.botao_cinemaTV.configure(state=DISABLED)
            self.botao_comedia.configure(state=DISABLED)
            self.botao_crime.configure(state=DISABLED)
            self.botao_drama.configure(state=DISABLED)
            self.botao_familia.configure(state=DISABLED)
            self.botao_fantasia.configure(state=DISABLED)
            self.botao_faroeste.configure(state=DISABLED)
            self.botao_guerra.configure(state=DISABLED)
            self.botao_historia.configure(state=DISABLED)
            self.botao_misterio.configure(state=DISABLED)
            self.botao_musica.configure(state=DISABLED)
            self.botao_romance.configure(state=DISABLED)
            self.botao_scifi.configure(state=DISABLED)
            self.botao_terror.configure(state=DISABLED)
            self.botao_thriller.configure(state=DISABLED)
        else:
            self.id_genero = None
            self.botao_acao.configure(state=NORMAL)
            self.botao_animacao.configure(state=NORMAL)
            self.botao_aventura.configure(state=NORMAL)
            self.botao_cinemaTV.configure(state=NORMAL)
            self.botao_comedia.configure(state=NORMAL)
            self.botao_crime.configure(state=NORMAL)
            self.botao_drama.configure(state=NORMAL)
            self.botao_familia.configure(state=NORMAL)
            self.botao_fantasia.configure(state=NORMAL)
            self.botao_faroeste.configure(state=NORMAL)
            self.botao_guerra.configure(state=NORMAL)
            self.botao_historia.configure(state=NORMAL)
            self.botao_misterio.configure(state=NORMAL)
            self.botao_musica.configure(state=NORMAL)
            self.botao_romance.configure(state=NORMAL)
            self.botao_scifi.configure(state=NORMAL)
            self.botao_terror.configure(state=NORMAL)
            self.botao_thriller.configure(state=NORMAL)
    
    def verificar_botao_drama(self):
        if self.botao_drama._check_state == True:
            self.id_genero = 18
            self.botao_acao.configure(state=DISABLED)
            self.botao_animacao.configure(state=DISABLED)
            self.botao_aventura.configure(state=DISABLED)
            self.botao_cinemaTV.configure(state=DISABLED)
            self.botao_comedia.configure(state=DISABLED)
            self.botao_crime.configure(state=DISABLED)
            self.botao_documentario.configure(state=DISABLED)
            self.botao_familia.configure(state=DISABLED)
            self.botao_fantasia.configure(state=DISABLED)
            self.botao_faroeste.configure(state=DISABLED)
            self.botao_guerra.configure(state=DISABLED)
            self.botao_historia.configure(state=DISABLED)
            self.botao_misterio.configure(state=DISABLED)
            self.botao_musica.configure(state=DISABLED)
            self.botao_romance.configure(state=DISABLED)
            self.botao_scifi.configure(state=DISABLED)
            self.botao_terror.configure(state=DISABLED)
            self.botao_thriller.configure(state=DISABLED)
        else:
            self.id_genero = None
            self.botao_acao.configure(state=NORMAL)
            self.botao_animacao.configure(state=NORMAL)
            self.botao_aventura.configure(state=NORMAL)
            self.botao_cinemaTV.configure(state=NORMAL)
            self.botao_comedia.configure(state=NORMAL)
            self.botao_crime.configure(state=NORMAL)
            self.botao_documentario.configure(state=NORMAL)
            self.botao_familia.configure(state=NORMAL)
            self.botao_fantasia.configure(state=NORMAL)
            self.botao_faroeste.configure(state=NORMAL)
            self.botao_guerra.configure(state=NORMAL)
            self.botao_historia.configure(state=NORMAL)
            self.botao_misterio.configure(state=NORMAL)
            self.botao_musica.configure(state=NORMAL)
            self.botao_romance.configure(state=NORMAL)
            self.botao_scifi.configure(state=NORMAL)
            self.botao_terror.configure(state=NORMAL)
            self.botao_thriller.configure(state=NORMAL)
    
    def verificar_botao_familia(self):
        if self.botao_familia._check_state == True:
            self.id_genero = 10751
            self.botao_acao.configure(state=DISABLED)
            self.botao_animacao.configure(state=DISABLED)
            self.botao_aventura.configure(state=DISABLED)
            self.botao_cinemaTV.configure(state=DISABLED)
            self.botao_comedia.configure(state=DISABLED)
            self.botao_crime.configure(state=DISABLED)
            self.botao_documentario.configure(state=DISABLED)
            self.botao_drama.configure(state=DISABLED)
            self.botao_fantasia.configure(state=DISABLED)
            self.botao_faroeste.configure(state=DISABLED)
            self.botao_guerra.configure(state=DISABLED)
            self.botao_historia.configure(state=DISABLED)
            self.botao_misterio.configure(state=DISABLED)
            self.botao_musica.configure(state=DISABLED)
            self.botao_romance.configure(state=DISABLED)
            self.botao_scifi.configure(state=DISABLED)
            self.botao_terror.configure(state=DISABLED)
            self.botao_thriller.configure(state=DISABLED)
        else:
            self.id_genero = None
            self.botao_acao.configure(state=NORMAL)
            self.botao_animacao.configure(state=NORMAL)
            self.botao_aventura.configure(state=NORMAL)
            self.botao_cinemaTV.configure(state=NORMAL)
            self.botao_comedia.configure(state=NORMAL)
            self.botao_crime.configure(state=NORMAL)
            self.botao_documentario.configure(state=NORMAL)
            self.botao_drama.configure(state=NORMAL)
            self.botao_fantasia.configure(state=NORMAL)
            self.botao_faroeste.configure(state=NORMAL)
            self.botao_guerra.configure(state=NORMAL)
            self.botao_historia.configure(state=NORMAL)
            self.botao_misterio.configure(state=NORMAL)
            self.botao_musica.configure(state=NORMAL)
            self.botao_romance.configure(state=NORMAL)
            self.botao_scifi.configure(state=NORMAL)
            self.botao_terror.configure(state=NORMAL)
            self.botao_thriller.configure(state=NORMAL)
    
    def verificar_botao_fantasia(self):
        if self.botao_fantasia._check_state == True:
            self.id_genero = 14
            self.botao_acao.configure(state=DISABLED)
            self.botao_animacao.configure(state=DISABLED)
            self.botao_aventura.configure(state=DISABLED)
            self.botao_cinemaTV.configure(state=DISABLED)
            self.botao_comedia.configure(state=DISABLED)
            self.botao_crime.configure(state=DISABLED)
            self.botao_documentario.configure(state=DISABLED)
            self.botao_drama.configure(state=DISABLED)
            self.botao_familia.configure(state=DISABLED)
            self.botao_faroeste.configure(state=DISABLED)
            self.botao_guerra.configure(state=DISABLED)
            self.botao_historia.configure(state=DISABLED)
            self.botao_misterio.configure(state=DISABLED)
            self.botao_musica.configure(state=DISABLED)
            self.botao_romance.configure(state=DISABLED)
            self.botao_scifi.configure(state=DISABLED)
            self.botao_terror.configure(state=DISABLED)
            self.botao_thriller.configure(state=DISABLED)
        else:
            self.id_genero = None
            self.botao_acao.configure(state=NORMAL)
            self.botao_animacao.configure(state=NORMAL)
            self.botao_aventura.configure(state=NORMAL)
            self.botao_cinemaTV.configure(state=NORMAL)
            self.botao_comedia.configure(state=NORMAL)
            self.botao_crime.configure(state=NORMAL)
            self.botao_documentario.configure(state=NORMAL)
            self.botao_drama.configure(state=NORMAL)
            self.botao_familia.configure(state=NORMAL)
            self.botao_faroeste.configure(state=NORMAL)
            self.botao_guerra.configure(state=NORMAL)
            self.botao_historia.configure(state=NORMAL)
            self.botao_misterio.configure(state=NORMAL)
            self.botao_musica.configure(state=NORMAL)
            self.botao_romance.configure(state=NORMAL)
            self.botao_scifi.configure(state=NORMAL)
            self.botao_terror.configure(state=NORMAL)
            self.botao_thriller.configure(state=NORMAL)
    
    def verificar_botao_faroeste(self):
        if self.botao_faroeste._check_state == True:
            self.id_genero = 37
            self.botao_acao.configure(state=DISABLED)
            self.botao_animacao.configure(state=DISABLED)
            self.botao_aventura.configure(state=DISABLED)
            self.botao_cinemaTV.configure(state=DISABLED)
            self.botao_comedia.configure(state=DISABLED)
            self.botao_crime.configure(state=DISABLED)
            self.botao_documentario.configure(state=DISABLED)
            self.botao_drama.configure(state=DISABLED)
            self.botao_familia.configure(state=DISABLED)
            self.botao_fantasia.configure(state=DISABLED)
            self.botao_guerra.configure(state=DISABLED)
            self.botao_historia.configure(state=DISABLED)
            self.botao_misterio.configure(state=DISABLED)
            self.botao_musica.configure(state=DISABLED)
            self.botao_romance.configure(state=DISABLED)
            self.botao_scifi.configure(state=DISABLED)
            self.botao_terror.configure(state=DISABLED)
            self.botao_thriller.configure(state=DISABLED)
        else:
            self.id_genero = None
            self.botao_acao.configure(state=NORMAL)
            self.botao_animacao.configure(state=NORMAL)
            self.botao_aventura.configure(state=NORMAL)
            self.botao_cinemaTV.configure(state=NORMAL)
            self.botao_comedia.configure(state=NORMAL)
            self.botao_crime.configure(state=NORMAL)
            self.botao_documentario.configure(state=NORMAL)
            self.botao_drama.configure(state=NORMAL)
            self.botao_familia.configure(state=NORMAL)
            self.botao_fantasia.configure(state=NORMAL)
            self.botao_guerra.configure(state=NORMAL)
            self.botao_historia.configure(state=NORMAL)
            self.botao_misterio.configure(state=NORMAL)
            self.botao_musica.configure(state=NORMAL)
            self.botao_romance.configure(state=NORMAL)
            self.botao_scifi.configure(state=NORMAL)
            self.botao_terror.configure(state=NORMAL)
            self.botao_thriller.configure(state=NORMAL)
    
    def verificar_botao_guerra(self):
        if self.botao_guerra._check_state == True:
            self.id_genero = 10752
            self.botao_acao.configure(state=DISABLED)
            self.botao_animacao.configure(state=DISABLED)
            self.botao_aventura.configure(state=DISABLED)
            self.botao_cinemaTV.configure(state=DISABLED)
            self.botao_comedia.configure(state=DISABLED)
            self.botao_crime.configure(state=DISABLED)
            self.botao_documentario.configure(state=DISABLED)
            self.botao_drama.configure(state=DISABLED)
            self.botao_familia.configure(state=DISABLED)
            self.botao_fantasia.configure(state=DISABLED)
            self.botao_faroeste.configure(state=DISABLED)
            self.botao_historia.configure(state=DISABLED)
            self.botao_misterio.configure(state=DISABLED)
            self.botao_musica.configure(state=DISABLED)
            self.botao_romance.configure(state=DISABLED)
            self.botao_scifi.configure(state=DISABLED)
            self.botao_terror.configure(state=DISABLED)
            self.botao_thriller.configure(state=DISABLED)
        else:
            self.id_genero = None
            self.botao_acao.configure(state=NORMAL)
            self.botao_animacao.configure(state=NORMAL)
            self.botao_aventura.configure(state=NORMAL)
            self.botao_cinemaTV.configure(state=NORMAL)
            self.botao_comedia.configure(state=NORMAL)
            self.botao_crime.configure(state=NORMAL)
            self.botao_documentario.configure(state=NORMAL)
            self.botao_drama.configure(state=NORMAL)
            self.botao_familia.configure(state=NORMAL)
            self.botao_fantasia.configure(state=NORMAL)
            self.botao_faroeste.configure(state=NORMAL)
            self.botao_historia.configure(state=NORMAL)
            self.botao_misterio.configure(state=NORMAL)
            self.botao_musica.configure(state=NORMAL)
            self.botao_romance.configure(state=NORMAL)
            self.botao_scifi.configure(state=NORMAL)
            self.botao_terror.configure(state=NORMAL)
            self.botao_thriller.configure(state=NORMAL)
    
    def verificar_botao_historia(self):
        if self.botao_historia._check_state == True:
            self.id_genero = 36
            self.botao_acao.configure(state=DISABLED)
            self.botao_animacao.configure(state=DISABLED)
            self.botao_aventura.configure(state=DISABLED)
            self.botao_cinemaTV.configure(state=DISABLED)
            self.botao_comedia.configure(state=DISABLED)
            self.botao_crime.configure(state=DISABLED)
            self.botao_documentario.configure(state=DISABLED)
            self.botao_drama.configure(state=DISABLED)
            self.botao_familia.configure(state=DISABLED)
            self.botao_fantasia.configure(state=DISABLED)
            self.botao_faroeste.configure(state=DISABLED)
            self.botao_guerra.configure(state=DISABLED)
            self.botao_misterio.configure(state=DISABLED)
            self.botao_musica.configure(state=DISABLED)
            self.botao_romance.configure(state=DISABLED)
            self.botao_scifi.configure(state=DISABLED)
            self.botao_terror.configure(state=DISABLED)
            self.botao_thriller.configure(state=DISABLED)
        else:
            self.id_genero = None
            self.botao_acao.configure(state=NORMAL)
            self.botao_animacao.configure(state=NORMAL)
            self.botao_aventura.configure(state=NORMAL)
            self.botao_cinemaTV.configure(state=NORMAL)
            self.botao_comedia.configure(state=NORMAL)
            self.botao_crime.configure(state=NORMAL)
            self.botao_documentario.configure(state=NORMAL)
            self.botao_drama.configure(state=NORMAL)
            self.botao_familia.configure(state=NORMAL)
            self.botao_fantasia.configure(state=NORMAL)
            self.botao_faroeste.configure(state=NORMAL)
            self.botao_guerra.configure(state=NORMAL)
            self.botao_misterio.configure(state=NORMAL)
            self.botao_musica.configure(state=NORMAL)
            self.botao_romance.configure(state=NORMAL)
            self.botao_scifi.configure(state=NORMAL)
            self.botao_terror.configure(state=NORMAL)
            self.botao_thriller.configure(state=NORMAL)
    
    def verificar_botao_misterio(self):
        if self.botao_misterio._check_state == True:
            self.id_genero = 9648
            self.botao_acao.configure(state=DISABLED)
            self.botao_animacao.configure(state=DISABLED)
            self.botao_aventura.configure(state=DISABLED)
            self.botao_cinemaTV.configure(state=DISABLED)
            self.botao_comedia.configure(state=DISABLED)
            self.botao_crime.configure(state=DISABLED)
            self.botao_documentario.configure(state=DISABLED)
            self.botao_drama.configure(state=DISABLED)
            self.botao_familia.configure(state=DISABLED)
            self.botao_fantasia.configure(state=DISABLED)
            self.botao_faroeste.configure(state=DISABLED)
            self.botao_guerra.configure(state=DISABLED)
            self.botao_historia.configure(state=DISABLED)
            self.botao_musica.configure(state=DISABLED)
            self.botao_romance.configure(state=DISABLED)
            self.botao_scifi.configure(state=DISABLED)
            self.botao_terror.configure(state=DISABLED)
            self.botao_thriller.configure(state=DISABLED)
        else:
            self.id_genero = None
            self.botao_acao.configure(state=NORMAL)
            self.botao_animacao.configure(state=NORMAL)
            self.botao_aventura.configure(state=NORMAL)
            self.botao_cinemaTV.configure(state=NORMAL)
            self.botao_comedia.configure(state=NORMAL)
            self.botao_crime.configure(state=NORMAL)
            self.botao_documentario.configure(state=NORMAL)
            self.botao_drama.configure(state=NORMAL)
            self.botao_familia.configure(state=NORMAL)
            self.botao_fantasia.configure(state=NORMAL)
            self.botao_faroeste.configure(state=NORMAL)
            self.botao_guerra.configure(state=NORMAL)
            self.botao_historia.configure(state=NORMAL)
            self.botao_musica.configure(state=NORMAL)
            self.botao_romance.configure(state=NORMAL)
            self.botao_scifi.configure(state=NORMAL)
            self.botao_terror.configure(state=NORMAL)
            self.botao_thriller.configure(state=NORMAL)
    
    def verificar_botao_musica(self):
        if self.botao_musica._check_state == True:
            self.id_genero = 10402
            self.botao_acao.configure(state=DISABLED)
            self.botao_animacao.configure(state=DISABLED)
            self.botao_aventura.configure(state=DISABLED)
            self.botao_cinemaTV.configure(state=DISABLED)
            self.botao_comedia.configure(state=DISABLED)
            self.botao_crime.configure(state=DISABLED)
            self.botao_documentario.configure(state=DISABLED)
            self.botao_drama.configure(state=DISABLED)
            self.botao_familia.configure(state=DISABLED)
            self.botao_fantasia.configure(state=DISABLED)
            self.botao_faroeste.configure(state=DISABLED)
            self.botao_guerra.configure(state=DISABLED)
            self.botao_historia.configure(state=DISABLED)
            self.botao_misterio.configure(state=DISABLED)
            self.botao_romance.configure(state=DISABLED)
            self.botao_scifi.configure(state=DISABLED)
            self.botao_terror.configure(state=DISABLED)
            self.botao_thriller.configure(state=DISABLED)
        else:
            self.id_genero = None
            self.botao_acao.configure(state=NORMAL)
            self.botao_animacao.configure(state=NORMAL)
            self.botao_aventura.configure(state=NORMAL)
            self.botao_cinemaTV.configure(state=NORMAL)
            self.botao_comedia.configure(state=NORMAL)
            self.botao_crime.configure(state=NORMAL)
            self.botao_documentario.configure(state=NORMAL)
            self.botao_drama.configure(state=NORMAL)
            self.botao_familia.configure(state=NORMAL)
            self.botao_fantasia.configure(state=NORMAL)
            self.botao_faroeste.configure(state=NORMAL)
            self.botao_guerra.configure(state=NORMAL)
            self.botao_historia.configure(state=NORMAL)
            self.botao_misterio.configure(state=NORMAL)
            self.botao_romance.configure(state=NORMAL)
            self.botao_scifi.configure(state=NORMAL)
            self.botao_terror.configure(state=NORMAL)
            self.botao_thriller.configure(state=NORMAL)
    
    def verificar_botao_romance(self):
        if self.botao_romance._check_state == True:
            self.id_genero = 10749
            self.botao_acao.configure(state=DISABLED)
            self.botao_animacao.configure(state=DISABLED)
            self.botao_aventura.configure(state=DISABLED)
            self.botao_cinemaTV.configure(state=DISABLED)
            self.botao_comedia.configure(state=DISABLED)
            self.botao_crime.configure(state=DISABLED)
            self.botao_documentario.configure(state=DISABLED)
            self.botao_drama.configure(state=DISABLED)
            self.botao_familia.configure(state=DISABLED)
            self.botao_fantasia.configure(state=DISABLED)
            self.botao_faroeste.configure(state=DISABLED)
            self.botao_guerra.configure(state=DISABLED)
            self.botao_historia.configure(state=DISABLED)
            self.botao_misterio.configure(state=DISABLED)
            self.botao_musica.configure(state=DISABLED)
            self.botao_scifi.configure(state=DISABLED)
            self.botao_terror.configure(state=DISABLED)
            self.botao_thriller.configure(state=DISABLED)
        else:
            self.id_genero = None
            self.botao_acao.configure(state=NORMAL)
            self.botao_animacao.configure(state=NORMAL)
            self.botao_aventura.configure(state=NORMAL)
            self.botao_cinemaTV.configure(state=NORMAL)
            self.botao_comedia.configure(state=NORMAL)
            self.botao_crime.configure(state=NORMAL)
            self.botao_documentario.configure(state=NORMAL)
            self.botao_drama.configure(state=NORMAL)
            self.botao_familia.configure(state=NORMAL)
            self.botao_fantasia.configure(state=NORMAL)
            self.botao_faroeste.configure(state=NORMAL)
            self.botao_guerra.configure(state=NORMAL)
            self.botao_historia.configure(state=NORMAL)
            self.botao_misterio.configure(state=NORMAL)
            self.botao_musica.configure(state=NORMAL)
            self.botao_scifi.configure(state=NORMAL)
            self.botao_terror.configure(state=NORMAL)
            self.botao_thriller.configure(state=NORMAL)
    
    def verificar_botao_scifi(self):
        if self.botao_scifi._check_state == True:
            self.id_genero = 878
            self.botao_acao.configure(state=DISABLED)
            self.botao_animacao.configure(state=DISABLED)
            self.botao_aventura.configure(state=DISABLED)
            self.botao_cinemaTV.configure(state=DISABLED)
            self.botao_comedia.configure(state=DISABLED)
            self.botao_crime.configure(state=DISABLED)
            self.botao_documentario.configure(state=DISABLED)
            self.botao_drama.configure(state=DISABLED)
            self.botao_familia.configure(state=DISABLED)
            self.botao_fantasia.configure(state=DISABLED)
            self.botao_faroeste.configure(state=DISABLED)
            self.botao_guerra.configure(state=DISABLED)
            self.botao_historia.configure(state=DISABLED)
            self.botao_misterio.configure(state=DISABLED)
            self.botao_musica.configure(state=DISABLED)
            self.botao_romance.configure(state=DISABLED)
            self.botao_terror.configure(state=DISABLED)
            self.botao_thriller.configure(state=DISABLED)
        else:
            self.id_genero = None
            self.botao_acao.configure(state=NORMAL)
            self.botao_animacao.configure(state=NORMAL)
            self.botao_aventura.configure(state=NORMAL)
            self.botao_cinemaTV.configure(state=NORMAL)
            self.botao_comedia.configure(state=NORMAL)
            self.botao_crime.configure(state=NORMAL)
            self.botao_documentario.configure(state=NORMAL)
            self.botao_drama.configure(state=NORMAL)
            self.botao_familia.configure(state=NORMAL)
            self.botao_fantasia.configure(state=NORMAL)
            self.botao_faroeste.configure(state=NORMAL)
            self.botao_guerra.configure(state=NORMAL)
            self.botao_historia.configure(state=NORMAL)
            self.botao_misterio.configure(state=NORMAL)
            self.botao_musica.configure(state=NORMAL)
            self.botao_romance.configure(state=NORMAL)
            self.botao_terror.configure(state=NORMAL)
            self.botao_thriller.configure(state=NORMAL)
    
    def verificar_botao_terror(self):
        if self.botao_terror._check_state == True:
            self.id_genero = 27
            self.botao_acao.configure(state=DISABLED)
            self.botao_animacao.configure(state=DISABLED)
            self.botao_aventura.configure(state=DISABLED)
            self.botao_cinemaTV.configure(state=DISABLED)
            self.botao_comedia.configure(state=DISABLED)
            self.botao_crime.configure(state=DISABLED)
            self.botao_documentario.configure(state=DISABLED)
            self.botao_drama.configure(state=DISABLED)
            self.botao_familia.configure(state=DISABLED)
            self.botao_fantasia.configure(state=DISABLED)
            self.botao_faroeste.configure(state=DISABLED)
            self.botao_guerra.configure(state=DISABLED)
            self.botao_historia.configure(state=DISABLED)
            self.botao_misterio.configure(state=DISABLED)
            self.botao_musica.configure(state=DISABLED)
            self.botao_romance.configure(state=DISABLED)
            self.botao_scifi.configure(state=DISABLED)
            self.botao_thriller.configure(state=DISABLED)
        else:
            self.id_genero = None
            self.botao_acao.configure(state=NORMAL)
            self.botao_animacao.configure(state=NORMAL)
            self.botao_aventura.configure(state=NORMAL)
            self.botao_cinemaTV.configure(state=NORMAL)
            self.botao_comedia.configure(state=NORMAL)
            self.botao_crime.configure(state=NORMAL)
            self.botao_documentario.configure(state=NORMAL)
            self.botao_drama.configure(state=NORMAL)
            self.botao_familia.configure(state=NORMAL)
            self.botao_fantasia.configure(state=NORMAL)
            self.botao_faroeste.configure(state=NORMAL)
            self.botao_guerra.configure(state=NORMAL)
            self.botao_historia.configure(state=NORMAL)
            self.botao_misterio.configure(state=NORMAL)
            self.botao_musica.configure(state=NORMAL)
            self.botao_romance.configure(state=NORMAL)
            self.botao_scifi.configure(state=NORMAL)
            self.botao_thriller.configure(state=NORMAL)
    
    def verificar_botao_thriller(self):
        if self.botao_thriller._check_state == True:
            self.id_genero = 53
            self.botao_acao.configure(state=DISABLED)
            self.botao_animacao.configure(state=DISABLED)
            self.botao_aventura.configure(state=DISABLED)
            self.botao_cinemaTV.configure(state=DISABLED)
            self.botao_comedia.configure(state=DISABLED)
            self.botao_crime.configure(state=DISABLED)
            self.botao_documentario.configure(state=DISABLED)
            self.botao_drama.configure(state=DISABLED)
            self.botao_familia.configure(state=DISABLED)
            self.botao_fantasia.configure(state=DISABLED)
            self.botao_faroeste.configure(state=DISABLED)
            self.botao_guerra.configure(state=DISABLED)
            self.botao_historia.configure(state=DISABLED)
            self.botao_misterio.configure(state=DISABLED)
            self.botao_musica.configure(state=DISABLED)
            self.botao_romance.configure(state=DISABLED)
            self.botao_scifi.configure(state=DISABLED)
            self.botao_terror.configure(state=DISABLED)
        else:
            self.id_genero = None
            self.botao_acao.configure(state=NORMAL)
            self.botao_animacao.configure(state=NORMAL)
            self.botao_aventura.configure(state=NORMAL)
            self.botao_cinemaTV.configure(state=NORMAL)
            self.botao_comedia.configure(state=NORMAL)
            self.botao_crime.configure(state=NORMAL)
            self.botao_documentario.configure(state=NORMAL)
            self.botao_drama.configure(state=NORMAL)
            self.botao_familia.configure(state=NORMAL)
            self.botao_fantasia.configure(state=NORMAL)
            self.botao_faroeste.configure(state=NORMAL)
            self.botao_guerra.configure(state=NORMAL)
            self.botao_historia.configure(state=NORMAL)
            self.botao_misterio.configure(state=NORMAL)
            self.botao_musica.configure(state=NORMAL)
            self.botao_romance.configure(state=NORMAL)
            self.botao_scifi.configure(state=NORMAL)
            self.botao_terror.configure(state=NORMAL)
  